import {connectivityQuality} from '../lib/connectivity-quality';
'use client';
import {rankPlatforms,type NetworkInputs} from '../lib/platform-compatibility';
export default function PlatformCompatibility({network,compact=false}:{network:NetworkInputs;compact?:boolean}){
 const s=rankPlatforms(network);
 const quality=connectivityQuality(network,s);
 return <section className="platform-guide"><div className={`connectivity-quality quality-${quality.level}`} aria-live="polite"><span className="eyebrow">ADEQUAÇÃO DA CONECTIVIDADE</span><h3>{quality.label}</h3><p>{quality.detail}</p><p className="small">{quality.teaching}</p><details><summary>Como interpretar esta escala</summary><p className="small">{quality.method}</p><p className="small">A média municipal de internet móvel é uma referência para planejamento; não representa a conexão da UBS ou de cada participante.</p></details></div><h3>Plataformas sugeridas para o curso</h3><div className="suggested-platforms"><article><span className="eyebrow">ENSINO</span><h4>{s.teachingSuggestion?.platform??'Complete os requisitos do curso'}</h4><p>{s.teachingSuggestion?s.teachingReason:'Informe recursos pedagógicos, estrutura existente e suporte para receber a sugestão.'}</p>{s.teachingSuggestion&&!compact&&<><small>{s.teachingSuggestion.detail.replace(/ \([+-]\d+\)/g,'')}</small><a href={s.teachingSuggestion.url} target="_blank" rel="noreferrer">Documentação oficial</a></>}</article><article><span className="eyebrow">VIDEOCONFERÊNCIA · {s.mode==='audio'?'ÁUDIO':'VÍDEO'}</span><h4>{s.conferenceSuggestion?.platform??(s.measured?'Validar requisitos e acesso':'Conectividade pendente')}</h4><p>{s.conferenceSuggestion?s.conferenceReason:s.measured?'Complete os requisitos. Se nenhuma opção atender à referência disponível, adapte o formato e valide a conexão local.':'Habilite os dados municipais e informe os requisitos dos encontros.'}</p>{s.conferenceSuggestion&&!compact&&<><small>Referência do perfil: upload {s.conferenceSuggestion.up} Mbps e download {s.conferenceSuggestion.down} Mbps. {s.conferenceSuggestion.detail}</small><a href={s.conferenceSuggestion.url} target="_blank" rel="noreferrer">Documentação oficial</a></>}</article></div>
 {s.measured&&!compact&&<p className="small">Anatel · referência {network.measurementDate}: download médio {network.download} Mbps e upload médio {network.upload} Mbps. {network.measurementPlace}.</p>}
 {!compact&&<details className="review-answers"><summary>Opções consideradas e critérios</summary><p>Ensino: Moodle, Google Classroom e Canvas LMS. A sugestão considera atividades, necessidade off-line, estrutura disponível e suporte; o orçamento limitado favorece aproveitar o ambiente existente. Empates recebem uma indicação inicial, sujeita ao piloto, e não demonstram superioridade.</p><p>Videoconferência: Teams, Meet, Zoom, Webex e BigBlueButton. Consideramos o perfil de banda, serviço existente e adequação declarada do plano. BigBlueButton exige infraestrutura dimensionada e suporte; sua referência básica de aluno não equivale aos perfis HD. Em áudio, Webex não é comparado numericamente porque não foi integrado um perfil específico.</p><p>Uma licença declarada insuficiente não é sugerida para uso imediato. As referências de fabricantes são de cenários diferentes: a indicação é de planejamento, não uma comparação de qualidade. Confirmar duração, participantes, gravação, presença e salas no plano efetivamente utilizado.</p><div className="platform-catalog">{s.teaching.map(p=><p key={p.id}><b>{p.platform}</b> · <a href={p.url} target="_blank" rel="noreferrer">Fonte oficial</a></p>)}{s.conference.map(p=><p key={p.id}><b>{p.platform}</b> · {p.licenseStatus} · <a href={p.url} target="_blank" rel="noreferrer">Fonte oficial</a></p>)}</div></details>}
 <p className="small platform-limits">Sugestões condicionadas à confirmação do serviço e ao teste da conexão local.</p></section>;
}
