'use client';
import {useEffect,useRef,useState} from 'react';
import {MapPin,Signal,Monitor,Info,Check,ChevronDown,BookOpen,CheckCircle2,ArrowUpRight} from 'lucide-react';
import snapshot from '../data/municipalities.json';
import speeds from '../data/municipal-speeds.json';
import type {Municipality} from '../lib/connectivity';
import {courseDecision,type EvidenceDecision} from '../lib/course-decision';
import {canAdvance,steps,type TrailState} from '../lib/trail';
import {finalGuidance} from '../lib/course-summary';
import {requirementOptions,visibleRequirements} from '../lib/platform-requirements';
import FinalSummary from '../components/final-summary';
import PlatformCompatibility from '../components/platform-compatibility';
import {dissertationAlerts} from '../lib/dissertation-alerts';
import {rankPlatforms} from '../lib/platform-compatibility';
import MunicipalQuality from '../components/municipal-quality';
type Data={municipality:Municipality;mode:string;retrieved:string;source:string;speed:{value:{period:string;samples:number;download:number;upload:number}|null;source:string;retrieved:string;method:string}};
const fmt=(v:number|null,d=1)=>v===null?'Sem dado':v.toLocaleString('pt-BR',{maximumFractionDigits:d,minimumFractionDigits:d});
const initial:TrailState={participants:'',parallelRooms:'',pedagogy:'',offlineNeed:'',teachingExisting:'',conferenceExisting:'',technicalSupport:'',meetingResources:'',licenseFit:'',audience:'',goal:'',uf:'',id:'',local:'unknown',mobile:'unknown',time:'',content:'',team:'',budget:'',lms:'',facilitation:'',specialist:'',acs:'',pilot:'',certification:'',measurementSource:'',measurementDate:'',measurementPlace:'',download:'',upload:'',devices:'1',skipData:false};
function Select({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][];disabled?:boolean}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}><option value="">Selecione uma resposta</option>{options.map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label>}
function Evidence({items,alerts}:{items:EvidenceDecision[];alerts:Record<string,string>}){const visible=items.filter(a=>alerts[a.id]);if(!visible.length)return null;return <aside className="stage-evidence dissertation-alert" role="status"><span className="eyebrow">ALERTA · O QUE A DISSERTAÇÃO ORIENTA</span>{visible.map(a=><details className="evidence-item" key={a.id}><summary><span><b>{a.title}</b><span>{alerts[a.id]} {['tracks','digital'].includes(a.id)?'':a.action}</span></span><ChevronDown size={17}/></summary><div className="evidence-detail"><b>Achado observado</b><p>{a.finding}</p><small>Lima, 2026 · {a.reference}</small></div></details>)}</aside>}

const yesno:[string,string][]=[['yes','Sim'],['no','Não'],['unknown','Ainda não confirmado']];
export default function Page(){
 const [step,setStep]=useState(0),[values,setValues]=useState<TrailState>(initial),[list,setList]=useState<{id:string;name:string;uf:string}[]>([]),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[listError,setListError]=useState(false),[finished,setFinished]=useState(false);
 const stageRef=useRef<HTMLDivElement>(null);
 const set=<K extends keyof TrailState>(key:K,value:TrailState[K])=>{setValues(v=>({...v,[key]:value,...(['participants','parallelRooms','meetingResources'].includes(key)?{licenseFit:''}:{})}));setFinished(false)};
 useEffect(()=>{setList(snapshot.map(({id,name,uf})=>({id,name,uf})))},[]);
 useEffect(()=>{if(!values.id){setData(null);return}setLoading(false);setError('');const municipality=snapshot.find(m=>m.id===values.id);if(!municipality){setData(null);setError('Município sem registro na base incluída.');return}const m=(speeds.municipalities as Record<string,{period:string;samples:number;download:number;upload:number}>)[values.id]??null;setData({municipality,mode:'snapshot',source:'https://www.anatel.gov.br/dadosabertos/paineis_de_dados/meu_municipio/ibc.zip',retrieved:'2026-10-01T22:16:00Z',speed:{value:m,source:speeds.source,retrieved:speeds.retrieved,method:speeds.method}});setValues(v=>({...v,measurementSource:m?'anatel-municipal':'',measurementDate:m?.period??'',measurementPlace:m?`${municipality.name} · ${m.samples.toLocaleString('pt-BR')} medições · média de todas as prestadoras e tecnologias`:'',download:m?String(m.download):'',upload:m?String(m.upload):'',devices:'1'}))},[values.id]);
 useEffect(()=>{stageRef.current?.focus()},[step]);
 const network=rankPlatforms({...values,participants:visibleRequirements(values).includes('participants')?values.participants:'',parallelRooms:visibleRequirements(values).includes('parallelRooms')?values.parallelRooms:''});
 const plan=courseDecision({local:network.measured?(network.constrained?'municipal-limited':'municipal'):'unknown',budget:values.budget,time:values.time==='yes',specialist:values.specialist==='yes',facilitation:values.facilitation==='yes',mobile:values.mobile,acs:values.acs==='yes',goal:values.goal});
 const production=values.team==='none'?'Estabelecer parceria':values.content==='yes'?'Adaptar curso existente':values.content==='partial'?'Complementar conteúdo existente':'Desenvolver curso próprio';
 const pending=[!data?'Confirmar indicadores oficiais do município':'',values.pilot!=='done'?'Validar acesso e plataformas no piloto':'',values.time!=='yes'?'Pactuar tempo protegido':'',values.technicalSupport==='none'?'Definir suporte técnico':'',['teams','meet','zoom','webex','bbb'].includes(values.conferenceExisting)&&values.licenseFit==='no'?'Adequar o serviço de videoconferência':'',values.conferenceExisting&&['teams','meet','zoom','webex','bbb'].includes(values.conferenceExisting)&&values.licenseFit!=='yes'?'Verificar a licença para os requisitos selecionados':'',values.lms!=='yes'?'Definir plataforma, hospedagem e suporte':'',values.facilitation!=='yes'?'Designar responsável por acompanhamento e feedback':'',values.team!=='full'?'Garantir revisão por especialista e apoio pedagógico':'',values.specialist!=='yes'?'Pactuar apoio para discussão de casos':'',values.certification!=='yes'?'Definir certificação e critérios de conclusão':'',values.pilot!=='done'?(values.pilot==='adjust'?'Corrigir dificuldades observadas no piloto':'Executar piloto antes de ampliar'):''].filter(Boolean);

 const alerts=dissertationAlerts(values,network);
 const guidance=finalGuidance(values,plan.modality,production,pending);
 const advance=canAdvance(step,values,!!data&&data.municipality.id===values.id,!!error||listError,loading);
 const move=(n:number)=>{setStep(n);setFinished(false)};
 const result={municipality:data?.municipality.name??null,modality:plan.modality,production,actions:plan.actions,pending,stage:step+1,guidance,platforms:network,finished};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_course_recommendation',description:'Ler a etapa atual, as recomendações fundamentadas e as pendências da trilha de decisão do curso de CP no SUS.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Use um objeto vazio');return result}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[step,values,data,finished]);
 return <><div className="institutional-logos" aria-label="Instituições do estudo e do projeto"><a href="https://www.unifesp.br/" target="_blank" rel="noreferrer"><img src={import.meta.env.BASE_URL+"logo-unifesp.png"} alt="Unifesp — Universidade Federal de São Paulo" width={755} height={755}/></a><a href="https://www.telenordeste.com.br/" target="_blank" rel="noreferrer"><img src={import.meta.env.BASE_URL+"logo-telenordeste.png"} alt="Projeto TeleNordeste" width={2079} height={601}/></a><a href="https://www.bp.org.br/" target="_blank" rel="noreferrer"><img src={import.meta.env.BASE_URL+"logo-bp.png"} alt="BP — A Beneficência Portuguesa de São Paulo" width={424} height={144}/></a></div><header><div className="brand"><span>Fluxo decisório para planejamento de Teleducação em Cuidados Paliativos</span></div><span className="header-label">EDUCAÇÃO PERMANENTE NO SUS</span></header><main className="trail-main"><div className="heading"><div><div className="eyebrow">UMA DECISÃO DE CADA VEZ</div><h1>{finished?'Resultado do fluxo decisório para planejamento de teleducação em cuidados paliativos':'Planeje seu curso de Cuidados Paliativos.'}</h1></div></div><div className="trail-progress"><span>{finished?'Trilha concluída':`Etapa ${step+1} de ${steps.length}`}</span><span>{steps[step].phase}</span><div className="progress-track"><div style={{width:`${(step+1)/steps.length*100}%`}}/></div></div><div className="trail-layout"><aside className="trail-rail"><ol>{steps.map((s,i)=><li key={s.title}><button disabled={i>step} onClick={()=>move(i)} className={finished?'completed':i===step?'current':i<step?'completed':''} aria-current={!finished&&i===step?'step':undefined}><span>{finished||i<step?<Check size={15}/>:i+1}</span><div>{s.title}<small>{s.phase}</small></div></button></li>)}</ol></aside><div className="trail-content">{finished?<><FinalSummary values={values} data={data} plan={plan} production={production} pending={pending}/><button type="button" className="review-responses" onClick={()=>setFinished(false)}>Revisar respostas</button></>:<section className="panel stage" ref={stageRef} tabIndex={-1}><div className="eyebrow">ETAPA {step+1} · {steps[step].phase.toUpperCase()}</div><h2>{steps[step].question}</h2>
 {step===0&&<><div className="form-grid"><Select label="Quem será capacitado?" value={values.audience} onChange={v=>set('audience',v)} options={[["multi","Equipe multiprofissional"],["category","Categoria profissional específica"],["management","Gestores do SUS"]]}/><Select label="Qual é a prioridade educacional?" value={values.goal} onChange={v=>set('goal',v)} options={[["knowledge","Consolidar conhecimento"],["confidence","Desenvolver segurança percebida"],["practice","Aplicar o aprendizado no serviço"]]}/><Select label="ACS participarão?" value={values.acs} onChange={v=>set('acs',v)} options={yesno}/></div><Evidence alerts={alerts} items={[plan.actions[5],plan.actions[3]]}/></>}
 {step===1&&<><div className="form-grid"><Select label="Estado" value={values.uf} onChange={v=>{setValues(s=>({...s,uf:v,id:'',local:'unknown',mobile:'unknown',measurementSource:'',measurementDate:'',measurementPlace:'',download:'',upload:'',devices:'1',skipData:false}));setFinished(false)}} options={[...new Set(list.map(m=>m.uf))].sort().map(v=>[v,v])}/><Select label="Município" value={values.id} disabled={!values.uf} onChange={v=>{setValues(s=>({...s,id:v,local:'unknown',mobile:'unknown',measurementSource:'',measurementDate:'',measurementPlace:'',download:'',upload:'',devices:'1',skipData:false}));setFinished(false)}} options={list.filter(m=>m.uf===values.uf).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).map(m=>[m.id,m.name])}/></div>{loading&&<p role="status" className="route-note">Consultando os indicadores oficiais…</p>}{(error||listError)&&<div className="error" role="alert">{error||'A lista municipal não carregou. Atualize a página para tentar novamente.'}<label className="inline-check"><input type="checkbox" checked={values.skipData} onChange={e=>set('skipData',e.target.checked)}/>Continuar com os dados municipais pendentes</label></div>}{data&&<div className="connection-brief"><b>{data.municipality.name} · {data.municipality.uf}</b>{data.speed.value?<p>Anatel · {data.speed.value.period}: download {fmt(data.speed.value.download)} Mbps · upload {fmt(data.speed.value.upload)} Mbps.</p>:<p>Sem medições disponíveis.</p>}<small>Referência municipal de internet móvel; validar a conexão local.</small><MunicipalQuality download={data.speed.value?.download??null} upload={data.speed.value?.upload??null}/>{data.speed.value&&<label className="inline-check"><input type="checkbox" checked={values.measurementSource==='anatel-municipal'} onChange={e=>set('measurementSource',e.target.checked?'anatel-municipal':'')}/>Usar referência municipal</label>}</div>}<h3>Escolha das plataformas</h3><Select label="Recursos financeiros" value={values.budget} onChange={v=>set('budget',v)} options={[["low","Priorizar a estrutura existente"],["medium","Há recursos para produção e suporte"]]}/><div className="form-grid">{visibleRequirements(values).map(key=>{const o=requirementOptions[key];return <Select key={key} label={o.label} value={values[key as keyof typeof requirementOptions]} onChange={v=>{set(key as keyof typeof requirementOptions,v);if(key==='conferenceExisting')set('licenseFit','')}} options={o.options}/>})}</div><PlatformCompatibility network={values} compact showQuality={false}/><Evidence alerts={alerts} items={[plan.actions[1]]}/></>}
 {step===2&&<><Select label="A gestão pactuou tempo de estudo na jornada de trabalho?" value={values.time} onChange={v=>set('time',v)} options={yesno}/><Evidence alerts={alerts} items={[plan.actions[0]]}/></>}
 {step===3&&<><div className="form-grid"><Select label="Há conteúdo de CP que possa ser aproveitado?" value={values.content} onChange={v=>set('content',v)} options={[["yes","Sim, adequado ao público e ao território"],["partial","Parcialmente; será necessário complementar"],["no","Não, precisaremos produzir"]]}/><Select label="Que equipe está disponível?" value={values.team} onChange={v=>set('team',v)} options={[["full","CP + pedagogia + TI + administração"],["partial","Equipe disponível parcialmente"],["none","Sem equipe interna disponível"]]}/></div>{values.content&&values.team&&<div className="next-decision"><b>Caminho sugerido: {production}</b></div>}<Evidence alerts={alerts} items={[plan.actions[5]]}/></>}
 {step===4&&<><div className="form-grid"><Select label="A plataforma sugerida pode ser disponibilizada?" value={values.lms} onChange={v=>set('lms',v)} options={yesno}/><Select label="Há responsável por mediação e feedback?" value={values.facilitation} onChange={v=>set('facilitation',v)} options={yesno}/></div><Evidence alerts={alerts} items={[plan.actions[2]]}/></>}
 {step===5&&<><Select label="Há equipe e canal de telessaúde para apoiar a prática?" value={values.specialist} onChange={v=>set('specialist',v)} options={yesno}/><div className="next-decision"><b>{values.audience==='management'?'Aplicação proposta: plano de ação do serviço':'Aplicação proposta: caso do território e plano de cuidado'}</b></div><Evidence alerts={alerts} items={[plan.actions[4],plan.actions[3]]}/></>}
 {step===6&&<><div className="form-grid"><Select label="O piloto foi realizado?" value={values.pilot} onChange={v=>set('pilot',v)} options={[["notdone","Ainda não"],["adjust","Sim, e há ajustes necessários"],["done","Sim, com condições verificadas"]]}/><Select label="Certificação e critérios de conclusão estão definidos?" value={values.certification} onChange={v=>set('certification',v)} options={yesno}/></div></>}
 <div className="trail-actions"><button className="back-button" disabled={step===0} onClick={()=>move(step-1)}>Voltar</button><span>{advance?'Você pode avançar.':'Responda aos campos desta etapa para continuar.'}</span><button className="primary-button" disabled={!advance} onClick={()=>step===steps.length-1?setFinished(true):move(step+1)}>{step===steps.length-1?'Concluir trilha':'Continuar'}</button></div></section>}<details className="trail-source"><summary>Fontes e limites das recomendações <ChevronDown size={16}/></summary><div><p><b>Anatel:</b> médias de download e upload calculadas sobre a base oficial de medições móveis, no último mês disponível para cada município. Não representam a conexão da UBS. <a href="https://informacoes.anatel.gov.br/paineis/qualidade/medidas-de-velocidade-da-internet-movel" target="_blank" rel="noreferrer">Fonte e metodologia</a>.</p><p><b>Dissertação:</b> LIMA, Bruno Belo. <i>Teleducação em cuidados paliativos na Atenção Primária à Saúde: análise de conhecimento, autoeficácia e satisfação.</i> Documento de qualificação, Unifesp, Santos, 2026. Versão consultada: arquivo “2. Qualificacao_Bruno_Belo_01_10_26 colaborações Lúcia (4).docx”. <a href="https://chatgpt.com/api/library/files/libfile_2a90cf4bf8908191ba72d17f40a74dd2/download">Consultar documento</a>.</p><p>Estudo de um curso de 40 h, MA/PI/AL, com 59 participantes analisados, 72,9% na APS. Grupo único, sem controle ou randomização. Autoeficácia autorreferida; ausência de acompanhamento longitudinal e desfechos de pacientes. Comentários opcionais: 29 de 59 participantes, 58 unidades de registro, que não equivalem a pessoas.</p><p>As decisões são interpretações para planejamento. A trilha não é um algoritmo validado e não prevê a eficácia do curso no município.</p></div></details></div></div><footer><span>Planejar CP · Cuidados Paliativos no SUS</span><span>Análise · Design · Desenvolvimento · Implementação · Avaliação</span></footer></main></>;
}
