export type CourseInputs = {local:string;budget:string;time:boolean;specialist:boolean;facilitation:boolean;mobile:string;acs:boolean;goal:string};
export type EvidenceDecision = {id:string;title:string;finding:string;action:string;reference:string};
export function courseDecision(i:CourseInputs) {
 const synchronous=(i.local==='stable'||i.local==='municipal') && i.time;
 const modality=(i.local==='limited'||i.local==='municipal-limited')?'Assíncrono com baixo consumo de dados':synchronous && i.budget!=='low'?'Assíncrono + encontros síncronos':'Predominantemente assíncrono';
 const rationale=i.local==='municipal'&&i.time&&i.budget!=='low'?'As médias municipais atendem a pelo menos um perfil de vídeo e há tempo protegido. Combine estudo flexível com encontros síncronos condicionados à validação da conexão local.':(i.local==='limited'||i.local==='municipal-limited')?'As médias municipais ficam abaixo dos perfis de vídeo comparados. Priorize texto, áudio, vídeos compactados e download prévio; valide a conexão local.':!i.time?'O tempo de estudo ainda não foi pactuado. Priorize atividades flexíveis e recuperação assíncrona; condicione encontros obrigatórios à pactuação com a gestão.':i.local==='unknown'?'A conexão das unidades ainda precisa ser validada. Use materiais leves e teste o acesso antes de pactuar atividades ao vivo.':i.budget==='low'?'A referência municipal e o tempo pactuado favorecem planejar encontros pontuais após validação local. O orçamento favorece materiais reutilizados, preservando acompanhamento e feedback.':'Conexão local e tempo de estudo foram confirmados. Combine estudo flexível, interação e discussão de situações do serviço.';
 const actions:EvidenceDecision[]=[
  {id:'participation',title:'Participação e tempo protegido',finding:'556 inscritos → 288 iniciantes → 102 concluintes: 35,4% de conclusão entre iniciantes e 18,3% entre inscritos. Carga horária: média 8,6/10, a menor nota dos aspectos avaliados.',action:i.time?'Manter o tempo pactuado, oferecer recuperação e acompanhar abandono por módulo. As taxas do estudo são referências descritivas, não metas para seu curso.':'Pactuar tempo protegido antes de exigir presença ao vivo. Distribuir a carga horária e oferecer alternativas assíncronas. Não atribuir toda a não conclusão à falta de tempo.',reference:'§§ 5.1, 5.5.1, 5.6.2 e 5.7.2.1'},
  {id:'digital',title:'Usabilidade e uso de celular',finding:'Usabilidade e inclusão digital: 6 de 58 unidades de registro (10,34%). Os relatos mencionam login, presença, atividades e acesso apenas por celular; o uso exclusivo do celular não foi quantificado.',action:i.mobile==='yes'?'Projetar para celular: navegação simples, texto legível, arquivos leves e teste de login, quizzes e presença no aparelho.':i.mobile==='unknown'?'Levantar os dispositivos utilizados e testar toda a jornada no celular antes do piloto. A cobertura da Anatel não substitui esse diagnóstico.':'Testar também no celular, simplificar login e registro das atividades e oferecer suporte para dificuldades digitais.',reference:'§ 5.7.2.2'},
  {id:'facilitation',title:'Mediação e acompanhamento',finding:'Mediação pedagógica e corpo docente: 16 de 58 unidades de registro (27,6%). Os participantes valorizaram a didática, a proximidade e o acompanhamento da equipe.',action:i.facilitation?'Reservar agenda para dúvidas, feedback e contato com quem deixa de participar, mesmo em oferta predominantemente assíncrona.':'Definir quem acompanhará os participantes. Com recursos limitados, reservar parte da equipe para dúvidas e feedback, além da produção de conteúdo.',reference:'§§ 5.7.1.2 e 6.1'},
  {id:'learning',title:'Aprendizagem além da satisfação',finding:'Em 59 participantes, conhecimento: 2,98 → 3,07 (Δ 0,09; IC95% 0,01–0,18; p=0,032). Autoeficácia: 3,39 → 3,67 (Δ 0,28; IC95% 0,16–0,41; p<0,001), em escala 1–4. NPS: +91,5.',action:i.goal==='knowledge'?'Priorizar pré-teste, quizzes com feedback e retomada dos temas com maior dificuldade. O ganho total foi pequeno e nenhum item de conhecimento apresentou diferença significativa após ajuste.':i.goal==='confidence'?'Combinar casos, simulações e feedback com avaliação pré/pós da autoeficácia e do desempenho em situações propostas. Segurança percebida não demonstra competência clínica.':'Incluir tarefa aplicada no serviço e acompanhamento pós-curso. A dissertação não avaliou transferência sustentada nem desfechos de pacientes.',reference:'§§ 5.4, 5.5.1 e 6.2'},
  {id:'practice',title:'Ponte entre curso e serviço',finding:'Aplicabilidade percebida: 8,9/10. O curso de 40 h combinou 19 h de aulas, 3 h de encontros abertos, 1 h de teleconsultoria e 17 h complementares; a contribuição isolada de cada componente não foi medida.',action:i.specialist?(synchronous?'Pactuar discussão de um caso do território com especialista e feedback sobre avaliação e plano de cuidado.':'Manter casos do território e pactuar canal de apoio compatível com a conexão e a disponibilidade local; agendar teleconsultoria quando houver condições.'):'Planejar casos do território e buscar parceria para discussão com especialista. A ausência de telessaúde não impede começar, mas precisa constar como recurso a pactuar.',reference:'§§ 4.2, 5.5.1, 6.1 e 6.2'},
  {id:'tracks',title:i.acs?'Aprendizagem dos ACS':'Competências e perfis profissionais',finding:'67,8% da amostra não tinham formação prévia em CP, embora 61,0% já tivessem prestado esse cuidado. Na ANCOVA, médicos (β=0,33) e demais profissionais de nível superior (β=0,24) tiveram maior autoeficácia pós-curso que ACS, com ajuste basal.',action:i.acs?'Manter ACS no núcleo comum e adaptar casos, linguagem e avaliação às suas atribuições, com apoio pedagógico. A associação não demonstra que os ACS aprendem menos nem que a trilha é superior.':'Diagnosticar conhecimentos prévios e combinar núcleo comum com atividades adequadas às atribuições de cada categoria. A eficácia comparativa de trilhas não foi testada.',reference:'§§ 5.2, 5.5 e 6.2'},
 ];
 return {modality,rationale,synchronous,actions};
}
